ViewModels/LeaveTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HumanResources.ViewModels
{ 
    public class LeaveTypeViewModel
    {
        public string Code { get; set; }
        public string OldCode { get; set; }
        public string Description { get; set; }
        public string TotalAbsenceDays { get; set; }
        public string UnitofMeasure { get; set; }
        public string AnnualLeaveDaysType { get; set; }
    }
}

Controllers/LeaveTypesController.cs
using HumanResources.Models;
using HumanResources.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HumanResources.Controllers
{
    [Authorize]
    public class LeaveTypesController : Controller
    {
        LeaveManagementEntities _db = new LeaveManagementEntities();
        // GET: LeaveTypes
        public ActionResult Index()
        {
            return View(from leaveTypes in _db.LeaveTypes
                        select leaveTypes);
        }
        public ActionResult Create()
        {
            List<AnnualLeaveDaysType> _AnnualLeaveDaysType = new List<AnnualLeaveDaysType>();
            _AnnualLeaveDaysType.Add(new AnnualLeaveDaysType { Code = "Working Days", Description = "Working Days" });
            _AnnualLeaveDaysType.Add(new AnnualLeaveDaysType { Code = "Consecutive Days", Description = "Consecutive Days" });

            //
            List<UnitOfMeasure> _UnitOfMeasure = new List<UnitOfMeasure>();
            _UnitOfMeasure.Add(new UnitOfMeasure { Code = "DAY", Description = "Days" });


            ViewBag.UnitofMeasure = _UnitOfMeasure;
            ViewBag.AnnualLeaveDaysType = _AnnualLeaveDaysType;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLeaveType(ViewModels.LeaveTypeViewModel _LeaveTypeViewModel)
        {
            string message = null, status = null;

            try
            {
                var leavetype = new LeaveType { Code = _LeaveTypeViewModel.Code, Description = _LeaveTypeViewModel.Description, TotalAbsence = Convert.ToInt16(_LeaveTypeViewModel.TotalAbsenceDays), AnnualLeaveDaysType = _LeaveTypeViewModel.AnnualLeaveDaysType, UnitOfMeasure = _LeaveTypeViewModel.UnitofMeasure };
                
                using (var dbEntities = new LeaveManagementEntities())
                {
                    dbEntities.Configuration.ValidateOnSaveEnabled = false;
                    dbEntities.LeaveTypes.Add(leavetype);
                    dbEntities.SaveChanges();
                    status = "000";
                    message = "Leave type saved successfully";
                }
            }
            catch(Exception es)
            {
                message = es.Message;
                status = "999";
            }
            var _RequestResponse = new RequestResponse
            {
                Message = message,

                Status = status
            };

            return Json(JsonConvert.SerializeObject(_RequestResponse), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(string Id)
        {
            List<AnnualLeaveDaysType> _AnnualLeaveDaysType = new List<AnnualLeaveDaysType>();
            _AnnualLeaveDaysType.Add(new AnnualLeaveDaysType { Code = "Working Days", Description = "Working Days" });
            _AnnualLeaveDaysType.Add(new AnnualLeaveDaysType { Code = "Consecutive Days", Description = "Consecutive Days" });

            
            List<UnitOfMeasure> _UnitOfMeasure = new List<UnitOfMeasure>();
            _UnitOfMeasure.Add(new UnitOfMeasure { Code = "DAY", Description = "Days" });

            var _LeaveTypeViewModel = new LeaveTypeViewModel();

            try
            {
                using(var db = new LeaveManagementEntities())
                {
                    var leavetype = db.LeaveTypes.Where(x => x.Code == Id).FirstOrDefault();
                    if(leavetype != null)
                    {
                        _LeaveTypeViewModel.OldCode = Id;
                        _LeaveTypeViewModel.Code = leavetype.Code;
                        _LeaveTypeViewModel.TotalAbsenceDays = leavetype.TotalAbsence.ToString();
                        _LeaveTypeViewModel.Description = leavetype.Description;
                        _LeaveTypeViewModel.UnitofMeasure = leavetype.UnitOfMeasure;
                        _LeaveTypeViewModel.AnnualLeaveDaysType = leavetype.AnnualLeaveDaysType;
                    }
                }
            }
            catch(Exception es)
            {
                AppFunctions.WriteLog(es.Message);
            }


            ViewBag.UnitofMeasure = _UnitOfMeasure;
            ViewBag.AnnualLeaveDaysType = _AnnualLeaveDaysType;
            return View(_LeaveTypeViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateLeaveType(ViewModels.LeaveTypeViewModel leavetype)
        {
            string message = null, status = null;

            try
            {               
                using (var dbEntities = new LeaveManagementEntities())
                {
                    var _LeaveType = dbEntities.LeaveTypes.Where(x => x.Code == leavetype.OldCode).FirstOrDefault();

                    if (_LeaveType != null)
                    {
                        _LeaveType.Code = leavetype.Code;
                        _LeaveType.TotalAbsence = Convert.ToInt32(leavetype.TotalAbsenceDays);
                        _LeaveType.Description = leavetype.Description;
                        _LeaveType.UnitOfMeasure = leavetype.UnitofMeasure;
                        _LeaveType.AnnualLeaveDaysType = leavetype.AnnualLeaveDaysType;
                        dbEntities.SaveChanges();

                        status = "000";
                        message = "Leave type updated successfully";
                    }
                }
            }
            catch (Exception es)
            {
                message = es.Message;
                status = "999";
            }
            var _RequestResponse = new RequestResponse
            {
                Message = message,

                Status = status
            };

            return Json(JsonConvert.SerializeObject(_RequestResponse), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(string Id)
        {
            List<AnnualLeaveDaysType> _AnnualLeaveDaysType = new List<AnnualLeaveDaysType>();
            _AnnualLeaveDaysType.Add(new AnnualLeaveDaysType { Code = "Working Days", Description = "Working Days" });
            _AnnualLeaveDaysType.Add(new AnnualLeaveDaysType { Code = "Consecutive Days", Description = "Consecutive Days" });

            //
            List<UnitOfMeasure> _UnitOfMeasure = new List<UnitOfMeasure>();
            _UnitOfMeasure.Add(new UnitOfMeasure { Code = "DAY", Description = "Days" });

            var _LeaveTypeViewModel = new LeaveTypeViewModel();

            try
            {
                using (var db = new LeaveManagementEntities())
                {
                    var leavetype = db.LeaveTypes.Where(x => x.Code == Id).FirstOrDefault();
                    if (leavetype != null)
                    {
                        _LeaveTypeViewModel.OldCode = Id;
                        _LeaveTypeViewModel.Code = leavetype.Code;
                        _LeaveTypeViewModel.TotalAbsenceDays = leavetype.TotalAbsence.ToString();
                        _LeaveTypeViewModel.Description = leavetype.Description;
                        _LeaveTypeViewModel.UnitofMeasure = leavetype.UnitOfMeasure;
                        _LeaveTypeViewModel.AnnualLeaveDaysType = leavetype.AnnualLeaveDaysType;
                    }
                }
            }
            catch (Exception es)
            {
                AppFunctions.WriteLog(es.Message);
            }


            ViewBag.UnitofMeasure = _UnitOfMeasure;
            ViewBag.AnnualLeaveDaysType = _AnnualLeaveDaysType;
            return View();
        }
        [HttpPost]
        public ActionResult Delete(string Code)
        {
            string status = "", message = "";

            try
            {
                using (var db = new LeaveManagementEntities())
                {
                    var leavetype = db.LeaveTypes.Where(x => x.Code == Code).SingleOrDefault();

                    if (leavetype != null)
                    {
                        db.LeaveTypes.Remove(leavetype);
                        db.SaveChanges();
                        status = "000";
                        message = "Leave type " + Code + " has been successfully deleted";
                    }
                    else
                    {
                        status = "900";
                        message = "Couldn't find leave type " + Code;
                    }
                }
            }
            catch (Exception es)
            {
                message = es.Message;
            }

            var _RequestResponse = new RequestResponse
            {
                Status = status,
                Message = message
            };

            return Json(JsonConvert.SerializeObject(_RequestResponse), JsonRequestBehavior.AllowGet);
        }
    }
}

Views/LeaveTypes/Create.cshtml
@model HumanResources.ViewModels.LeaveTypeViewModel

@{
    ViewBag.Title = "Create Leave Type";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}




<div class="page-content">

    <div class="page-header">
        <h1>
            Leave Type
        </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <div class="widget-box">
                <div class="widget-header widget-header-blue widget-header-flat">
                    <h4 class="widget-title lighter">New Leave Type Wizard</h4>
                </div>

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">

                            <div class="step-content pos-rel">
                                <h3 class="lighter block green">Enter the following information</h3>

                                @using (Html.BeginForm("CreateLeaveType", "LeaveTypes", FormMethod.Post, new { @id = "leavetypeform", @class = "form-horizontal" }))
                                {
                                    @Html.AntiForgeryToken()

                                    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="name">Leave Type Code:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.Code, new { @class = "col-xs-12 col-sm-5" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.Code, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="Description">Description:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.Description, new { @class = "col-xs-12 col-sm-5" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="TotalAbsenceDays">Total Absence Days:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.TotalAbsenceDays, new { @class = "col-xs-12 col-sm-8" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.TotalAbsenceDays, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="hr hr-dotted"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="UnitofMeasure">Unit of Measure</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">

                                                @Html.DropDownListFor(m => m.UnitofMeasure,
                                                                    new SelectList(ViewBag.UnitofMeasure, "Code", "Description", ""),
                                                                    "Select UoM",
                                                                    new { @class = "select2", @data_placeholder = "Click to Choose..." })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.UnitofMeasure, "", new { @class = "text-danger  " })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="state">AnnualLeaveDaysType</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">

                                                @Html.DropDownListFor(m => m.AnnualLeaveDaysType,
                                                                    new SelectList(ViewBag.AnnualLeaveDaysType, "Code", "Description", ""),
                                                                    "Select leave days type",
                                                                    new { @class = "select2", @data_placeholder = "Click to Choose..." })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.AnnualLeaveDaysType, "", new { @class = "text-danger  " })
                                        </div>
                                    </div>

                                    <div class="space-8"></div>

                                }
                            </div>
                        </div>

                        <hr />
                        <div class="wizard-actions center">
                            <button class="btn btn-success btn-next" id="SaveLeaveType">
                                Save
                                <i class="ace-icon fa fa-floppy-o  icon-on-right"></i>
                            </button>
                        </div>
                    </div><!-- /.widget-main -->
                </div><!-- /.widget-body -->
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->

</div>

Views/LeaveTypes/Details.cshtml
@model HumanResources.ViewModels.LeaveTypeViewModel

@{
    ViewBag.Title = Model.Description + " Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content">

    <div class="page-header">
        <h1>
            View Leave Type - @Model.Description
        </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <div class="widget-box">
                <div class="widget-header widget-header-blue widget-header-flat">
                    <h4 class="widget-title lighter">View Leave Type</h4>
                </div>

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">

                            <div class="step-content pos-rel">
                                <h3 class="lighter block green">Enter the following information</h3>

                                @using (Html.BeginForm("CreateLeaveType", "LeaveTypes", FormMethod.Post, new { @id = "leavetypeform", @class = "form-horizontal" }))
                                {
                                    @Html.AntiForgeryToken()

                                    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="name">Leave Type Code:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.Code, new { @class = "col-xs-12 col-sm-5", @value = Model.Code, @disabled = "disabled" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.Code, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="Description">Description:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.Description, new { @class = "col-xs-12 col-sm-5", @value = Model.Description, @disabled = "disabled" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="TotalAbsenceDays">Total Absence Days:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.TotalAbsenceDays, new { @class = "col-xs-12 col-sm-8", @value = Model.TotalAbsenceDays, @disabled = "disabled" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.TotalAbsenceDays, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="hr hr-dotted"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="UnitofMeasure">Unit of Measure</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">

                                                @Html.DropDownListFor(m => m.UnitofMeasure,
                                                                    new SelectList(ViewBag.UnitofMeasure, "Code", "Description", Model.UnitofMeasure),
                                                                    "Select UoM",
                                                                    new { @class = "select2", @data_placeholder = "Click to Choose...", @disabled = "disabled" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.UnitofMeasure, "", new { @class = "text-danger  " })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="state">AnnualLeaveDaysType</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">

                                                @Html.DropDownListFor(m => m.AnnualLeaveDaysType,
                                                                    new SelectList(ViewBag.AnnualLeaveDaysType, "Code", "Description", Model.AnnualLeaveDaysType),
                                                                    "Select leave days type",
                                                                    new { @class = "select2", @data_placeholder = "Click to Choose...", @disabled = "disabled" })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.AnnualLeaveDaysType, "", new { @class = "text-danger  " })
                                        </div>
                                    </div>

                                    <div class="space-8"></div>


                                    @Html.HiddenFor(m => m.OldCode)
                                }
                            </div>
                        </div>

                        <hr />
                        <div class="wizard-actions center">
                            @*<button class="btn btn-success btn-next" id="SaveLeaveType">
                                Save
                                <i class="ace-icon fa fa-floppy-o  icon-on-right"></i>
                            </button>*@
                        </div>
                    </div><!-- /.widget-main -->
                </div><!-- /.widget-body -->
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->

</div>

Views/LeaveTypes/Edit.cshtml
@model HumanResources.ViewModels.LeaveTypeViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content">

    <div class="page-header">
        <h1>
            Edit Leave Type
        </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->

            <div class="widget-box">
                <div class="widget-header widget-header-blue widget-header-flat">
                    <h4 class="widget-title lighter">New Leave Type Wizard</h4>
                </div>

                <div class="widget-body">
                    <div class="widget-main">
                        <div id="fuelux-wizard-container">

                            <div class="step-content pos-rel">
                                <h3 class="lighter block green">Enter the following information</h3>

                                @using (Html.BeginForm("CreateLeaveType", "LeaveTypes", FormMethod.Post, new { @id = "leavetypeform", @class = "form-horizontal" }))
                                {
                                    @Html.AntiForgeryToken()

                                    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="name">Leave Type Code:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.Code, new { @class = "col-xs-12 col-sm-5", @value = Model.Code })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.Code, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="Description">Description:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.Description, new { @class = "col-xs-12 col-sm-5", @value = Model.Description })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="TotalAbsenceDays">Total Absence Days:</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">
                                                @Html.TextBoxFor(m => m.TotalAbsenceDays, new { @class = "col-xs-12 col-sm-8", @value = Model.TotalAbsenceDays })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.TotalAbsenceDays, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="hr hr-dotted"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="UnitofMeasure">Unit of Measure</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">

                                                @Html.DropDownListFor(m => m.UnitofMeasure,
                                                                    new SelectList(ViewBag.UnitofMeasure, "Code", "Description", Model.UnitofMeasure),
                                                                    "Select UoM",
                                                                    new { @class = "select2", @data_placeholder = "Click to Choose..." })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.UnitofMeasure, "", new { @class = "text-danger  " })
                                        </div>
                                    </div>

                                    <div class="space-2"></div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="state">AnnualLeaveDaysType</label>

                                        <div class="col-xs-12 col-sm-9">
                                            <div class="clearfix">

                                                @Html.DropDownListFor(m => m.AnnualLeaveDaysType,
                                                                    new SelectList(ViewBag.AnnualLeaveDaysType, "Code", "Description", Model.AnnualLeaveDaysType),
                                                                    "Select leave days type",
                                                                    new { @class = "select2", @data_placeholder = "Click to Choose..." })
                                            </div>
                                            @Html.ValidationMessageFor(m => m.AnnualLeaveDaysType, "", new { @class = "text-danger  " })
                                        </div>
                                    </div>

                                    <div class="space-8"></div>


                                    @Html.HiddenFor(m => m.OldCode)
                                }
                            </div>
                        </div>

                        <hr />
                        <div class="wizard-actions center">
                            <button class="btn btn-success btn-next" id="UpdateLeaveType">
                                Save
                                <i class="ace-icon fa fa-floppy-o  icon-on-right"></i>
                            </button>
                        </div>
                    </div><!-- /.widget-main -->
                </div><!-- /.widget-body -->
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->

</div>