Models/ApprovalEntry.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalEntry
    {
        public int EntryNumber { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNo { get; set; }
        public string SenderId { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string ApproverId { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<int> Status { get; set; }
    }
}

Controllers/ApprovalEntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HumanResources.Controllers
{
    using Models;
    using Newtonsoft.Json;
    using HumanResources.ViewModels;
    using HumanResources.CustomFunctions;
    using System.IO;
    using System.Threading.Tasks;

    [Authorize(Roles = "LeaveApprover")]
    public class ApprovalEntriesController : Controller
    {
        private static LeaveManagementEntities _db = new LeaveManagementEntities();
        // GET: ApprovalEntries
        public ActionResult Index()
        {
            string status = Request.QueryString["status"];

            int approvalentrystatus = 0;

            if (string.IsNullOrEmpty(status))
                return HttpNotFound();

            if (status == "pending")
            {
                approvalentrystatus = (int)DocumentApprovalStatus.Open;
            }

            if (status == "approved")
            {
                approvalentrystatus = (int)DocumentApprovalStatus.Approved;
            }

            if (status == "rejected")
            {
                approvalentrystatus = (int)DocumentApprovalStatus.Rejected;
            }

            string ApproverId = HttpContext.Session["EmployeeNo"].ToString();

            List<ApprovalEntriesListViewModel> _ApprovalEntriesListViewModel = new List<ApprovalEntriesListViewModel>();

            var approvalentries = _db.ApprovalEntries.Where(a => a.Status == approvalentrystatus && a.ApproverId == ApproverId).ToList();

            foreach (var approvalentry in approvalentries)
            {
                _ApprovalEntriesListViewModel.Add(new ApprovalEntriesListViewModel { EntryNo = approvalentry.EntryNumber, DocumentType = "Leave", DocumentNo = approvalentry.DocumentNo, DateSubmitted = AppFunctions.GetReadableDate((approvalentry.DateSent).ToString()), EmployeeName = approvalentry.SenderId, EndDate = "July 6 2021", LeaveDays = "1", StartDate = "July 6 2021", ApprovedLeaveType = "Annual Leave", ApprovalStatus = approvalentry.Status.ToString() });
            }
            return View(_ApprovalEntriesListViewModel);
        }
        public async Task<JsonResult> Approve(int EntryNo)
        {
            string status = "", message = "";

            var approvalentries = _db.ApprovalEntries.Where(a => a.EntryNumber == EntryNo).FirstOrDefault();

            if(approvalentries!= null)
            {
                int SequenceNo = Convert.ToInt32(approvalentries.SequenceNo);
                string DocumentNo = approvalentries.DocumentNo;

                string approvalrequestresponse = MakerChecker.ApproveAppovalRequest(EntryNo, SequenceNo, "Leave", DocumentNo);

                ApprovedRequestResponse _ApprovedRequestResponse = JsonConvert.DeserializeObject<ApprovedRequestResponse>(approvalrequestresponse);

                status = _ApprovedRequestResponse.Status;

                if (status == "000")
                {
                    string body = string.Empty;

                    string domainName = Request.Url.GetLeftPart(UriPartial.Authority);

                    string url = Url.Action("Login", "Account");

                    string pathToTemplate = Server.MapPath("~/MailTemplates/ApprovalCompletedNotification.html");

                    using (StreamReader reader = new StreamReader(pathToTemplate))
                    {
                        body = reader.ReadToEnd();
                    }
                    body = body.Replace("{Link}", domainName + url);
                    body = body.Replace("{LeaveNo}", _ApprovedRequestResponse.DocumentNo);
                    body = body.Replace("{UserName}", _ApprovedRequestResponse.SenderEmail);

                    bool IsSendEmail = await Task.Run(() =>EmailFunctions.SendMailAsync(_ApprovedRequestResponse.SenderEmail, _ApprovedRequestResponse.SenderEmail, "Approval Complete!", body));


                    status = "000";
                    message = "Approval success for leave " + approvalentries.DocumentNo;
                }
                else
                {
                    status = "999";
                    message = "Approval failed for leave " + approvalentries.DocumentNo;
                }
            }
            else
            {
                status = "999";
                message = "Approval entry not found";
            }           

            var _RequestResponse = new RequestResponse
            {
                Status = status,
                Message = message
            };

            return Json(JsonConvert.SerializeObject(_RequestResponse), JsonRequestBehavior.AllowGet);
        }
        public async Task<JsonResult> Reject(int EntryNo, string Comment)
        {
            string status = "", message = "";

            string ApproverId = HttpContext.Session["EmployeeNo"].ToString();

            var approvalentries = _db.ApprovalEntries.Where(a => a.EntryNumber == EntryNo).FirstOrDefault();

            if (approvalentries != null)
            {
                int SequenceNo = Convert.ToInt32(approvalentries.SequenceNo);
                string DocumentNo = approvalentries.DocumentNo;

                string approvalrequestresponse = MakerChecker.RejectAppovalRequest(EntryNo, "Leave", DocumentNo, ApproverId, Comment);

                ApprovedRequestResponse _ApprovedRequestResponse = JsonConvert.DeserializeObject<ApprovedRequestResponse>(approvalrequestresponse);

                status = _ApprovedRequestResponse.Status;

                if (status == "000")
                {
                    string body = string.Empty;

                    string domainName = Request.Url.GetLeftPart(UriPartial.Authority);

                    string url = Url.Action("Login", "Account");

                    string pathToTemplate = Server.MapPath("~/MailTemplates/ApprovalRejectedNotification.html");

                    using (StreamReader reader = new StreamReader(pathToTemplate))
                    {
                        body = reader.ReadToEnd();
                    }
                    body = body.Replace("{Link}", domainName + url);
                    body = body.Replace("{LeaveNo}", _ApprovedRequestResponse.DocumentNo);
                    body = body.Replace("{UserName}", _ApprovedRequestResponse.SenderEmail);

                    bool IsSendEmail = await Task.Run(() => EmailFunctions.SendMailAsync(_ApprovedRequestResponse.SenderEmail, _ApprovedRequestResponse.SenderEmail, "Approval Rejected !", body));


                    status = "000";
                    message = "Rejection success for leave " + approvalentries.DocumentNo;
                }
                else
                {
                    status = "999";
                    message = "Rejection failed for leave " + approvalentries.DocumentNo;
                }
            }
            else
            {
                status = "999";
                message = "Approval entry not found";
            }

            var _RequestResponse = new RequestResponse
            {
                Status = status,
                Message = message
            };

            return Json(JsonConvert.SerializeObject(_RequestResponse), JsonRequestBehavior.AllowGet);
        }
        public ActionResult ViewApprovalEntries(string id)
        {
            return RedirectToAction("ViewLeave", "Leaves", new { id = id });
        }
    }
}

Views/ApprovalEntries/Index.cshtml
@model IEnumerable<HumanResources.ViewModels.ApprovalEntriesListViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content">

    <div class="page-header">
        <h1>
            Approval Entries
        </h1>
    </div>
    <!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="clearfix">
                        <div class="pull-right tableTools-container"></div>
                    </div>
                    <div class="table-header">
                        Results for "Approval entries"
                    </div>

                    <!-- div.table-responsive -->
                    <!-- div.dataTables_borderWrap -->
                    <div>
                        <table id="approvalentries-table" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th class="center">
                                        <label class="pos-rel">
                                            <input type="checkbox" class="ace" />
                                            <span class="lbl"></span>
                                        </label>
                                    </th>

                                    <th>
                                        <i class="ace-icon fa fa-clipboard bigger-110 hidden-480"></i>
                                        Document Type
                                    </th>
                                    <th>
                                        <i class="ace-icon fa fa-list-ol bigger-110 hidden-480"></i>
                                        Document No.
                                    </th> 
                                    <th class="hidden-480">
                                        <i class="ace-icon fa fa-calendar bigger-110 hidden-480"></i>
                                        Date Submitted
                                    </th>
                                    <th>
                                        <i class="ace-icon fa fa-user bigger-110 hidden-480"></i>
                                        Employee Name
                                    </th>
                                    <th>
                                        <i class="ace-icon fa fa-calendar bigger-110 hidden-480"></i>
                                        Start Date
                                    </th>
                                    <th class="hidden-480">
                                        <i class="ace-icon fa fa-calendar bigger-110 hidden-480"></i>
                                        End Date
                                    </th>

                                    <th>
                                        <i class="ace-icon fa fa-calendar bigger-110 hidden-480"></i>
                                        Leave Days
                                    </th>
                                    <th class="hidden-480">
                                        <i class="ace-icon fa fa-question-circle bigger-110 hidden-480"></i>
                                        Status
                                    </th>


                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach (var approvalentry in Model)
                                {
                                <tr>
                                    <td class="center">
                                        <label class="pos-rel">
                                            <input type="checkbox" class="ace" />
                                            <span class="lbl"></span>
                                        </label>
                                    </td>

                                    <td>
                                        <a href="#">@approvalentry.DocumentType</a>
                                    </td>
                                    <td>@approvalentry.DocumentNo</td>
                                    <td class="hidden-480">@approvalentry.DateSubmitted</td>
                                    <td>@approvalentry.EmployeeName</td>
                                    <td>@approvalentry.StartDate</td>
                                    <td class="hidden-480">@approvalentry.EndDate</td>
                                    <td>@approvalentry.LeaveDays</td>

                                    <td class="hidden-480">
                                        @if (approvalentry.ApprovalStatus == ((int)DocumentApprovalStatus.Open).ToString())
                                        {
                                            <span class="label label-sm label-warning">@((DocumentApprovalStatus)Convert.ToInt32(approvalentry.ApprovalStatus))</span>
                                        }
                                        else if (approvalentry.ApprovalStatus == ((int)DocumentApprovalStatus.ApprovalPending).ToString())
                                        {
                                            <span class="label label-sm label-warning">@((DocumentApprovalStatus)Convert.ToInt32(approvalentry.ApprovalStatus))</span>
                                        }
                                        else if (approvalentry.ApprovalStatus == ((int)DocumentApprovalStatus.Approved).ToString())
                                        {
                                            <span class="label label-sm label-success">@((DocumentApprovalStatus)Convert.ToInt32(approvalentry.ApprovalStatus))</span>
                                        }
                                        else if (approvalentry.ApprovalStatus == ((int)DocumentApprovalStatus.Rejected).ToString())
                                        {
                                            <span class="label label-sm label-danger">@((DocumentApprovalStatus)Convert.ToInt32(approvalentry.ApprovalStatus))</span>
                                        }
                                    </td>

                                    <td>
                                        <div class="hidden-sm hidden-xs action-buttons">
                                            <a class="blue" href="@Url.Action("ViewApprovalEntries", "ApprovalEntries", new { id = approvalentry.DocumentNo })">
                                                <i class="ace-icon fa fa-search-plus bigger-130"></i>
                                            </a>

                                            <a class="green appoveapprovalentry" href="#" data-id="@approvalentry.EntryNo" data-docno ="@approvalentry.DocumentNo">
                                                <i class="ace-icon fa fa-check bigger-130"></i>
                                            </a>

                                            <a class="red rejectapprovalentry" href="#" data-id="@approvalentry.EntryNo" data-docno="@approvalentry.DocumentNo">
                                                <i class="ace-icon fa fa-times bigger-130"></i>
                                            </a>
                                        </div>

                                        <div class="hidden-md hidden-lg">
                                            <div class="inline pos-rel">
                                                <button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                                    <i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
                                                </button>

                                                <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                    <li>
                                                        <a href="@Url.Action("View", "ApprovalEntries", new { id = approvalentry.DocumentNo  })" class="tooltip-info" data-rel="tooltip" title="View">
                                                            <span class="blue">
                                                                <i class="ace-icon fa fa-search-plus bigger-120"></i>
                                                            </span>
                                                        </a>
                                                    </li>

                                                    <li>
                                                        <a href="#" class="tooltip-success appoveapprovalentry" data-id="@approvalentry.EntryNo" data-docno="@approvalentry.DocumentNo" data-rel="tooltip" title="Approve">
                                                            <span class="green">
                                                                <i class="ace-icon fa fa-check-square-o bigger-120"></i>
                                                            </span>
                                                        </a>
                                                    </li>

                                                    <li>
                                                        <a href="#" class="tooltip-error rejectapprovalentry" data-id="@approvalentry.EntryNo" data-docno="@approvalentry.DocumentNo" data-rel="tooltip" title="Reject">
                                                            <span class="red">
                                                                <i class="ace-icon fa fa-times-circle-o bigger-120"></i>
                                                            </span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div>

@*Reject comment modal*@


<div id="rejectmodal-form" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="blue bigger">Please fill the following form fields</h4>
            </div>

            <div class="modal-body">
                @using (Html.BeginForm("Reject", "ApprovalEntries", FormMethod.Post, new { @id = "rejectapproval", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

                    <input type="hidden" id="EntryNo" />

                    <div class="form-group">
                        <label class="control-label col-xs-12 col-sm-3 no-padding-right" for="name">Rejecttion Comment:</label>

                        <div class="col-xs-12 col-sm-9">
                            <div class="clearfix">
                                <textarea id="Comment" class="autosize-transition limited form-control"> </textarea>
                            </div>

                        </div>
                    </div>
                }
            </div>

            <div class="modal-footer">
                <button class="btn btn-sm" data-dismiss="modal">
                    <i class="ace-icon fa fa-times"></i>
                    Cancel
                </button>

                <button class="btn btn-sm btn-primary" id="RejectApprovalEntryComment">
                    <i class="ace-icon fa fa-check"></i>
                    Save
                </button>
            </div>
        </div>
    </div>
</div>